node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
     sh 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list'
     sh 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -'
     sh 'sudo apt-get update'
     sh 'sudo apt-get install libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4'
     sh 'sudo apt-get install google-chrome-stable'
     sh 'sudo apt-get install xvfb gtk2-engines-pixbuf'
     sh 'sudo apt-get install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable'
     sh 'sudo apt-get install imagemagick x11-apps'
   }
   stage('test') {
       nodejs('nodejs') {
         sh 'npm run test-headless'
      }

   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("rajeshgn821/weatherapp:${commit_id}",'.').push()
     }
   }
}