version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    volumes:
      - "/usr/src/app/app-ui/node_modules"
      - .:/usr/src/app/app-ui
